### ISSUE TITLE
Unlink service does not work for me

### ISSUE THREAD

**Issue by 1v0dev** [ppanagiotis/pymusiccast#13]
I got the following config:
```media_player:
  - platform: musiccast_yamaha
    host: 192.168.0.52
    port: 5004
  - platform: musiccast_yamaha
    host: 192.168.0.53
    port: 5005
```

and in lovelace:
```          
          - type: button
            name: Join Office
            show_state: false
            tap_action:
              action: call-service
              service: musiccast_yamaha.join
              service_data:
                entity_id: media_player.speaker_main
                master: media_player.receiver_main
          - type: button
            name: Only Receiver
            show_state: false
            tap_action:
              action: call-service
              service: musiccast_yamaha.unjoin
              service_data:
                entity_id: media_player.speaker_main
```
The _Join Office_ button works fine and groups the speakers but the _Only Receiver_ one with the unjoin service does nothing. I tried calling the service from the dev screen in HASS but nothing happens there as well. Any thoughts?

**Comment by ppanagiotis** [comment]
Hello. Can you please try with:

```
service: musiccast_yamaha.unjoin
entity_id: media_player.speaker_main
```
Try removing `service_data`

**Comment by 1v0dev** [comment]
Hi, thanks for the support. Unfortunately, it does not work that way too. I tried with dev tools as well, calling the service does nothing. No errors in the HASS log too.
![image](https://user-images.githubusercontent.com/56637685/103209733-736eab80-490c-11eb-8ad4-02b6b6e0ce98.png)

**Comment by 1v0dev** [comment]
I will try creating an automation and calling that instead, to test if it works that way

**Comment by 1v0dev** [comment]
I tried running this automation, but again no result:
```
alias: unlink test
description: ''
trigger: []
condition: []
action:
  - service: musiccast_yamaha.unjoin
    entity_id: media_player.speaker_main
mode: single
```
