### ISSUE TITLE
Trying to get your music cast setup working

### ISSUE THREAD

**Issue by jdedfamily** [ppanagiotis/pymusiccast#3]
first of all thanks for putting the effort in to get this going .

I have a whole house music cast setup and have been playing around with your multi speaker setup but cannt get it working 

first setup i did was add the following to the configuration file , this was in addition to the same devices i had added under  **platform: yamaha_musiccast** same ports 

```   - platform: musiccast_yamaha
    host: 192.xxx
    port: 5005
  - platform: musiccast_yamaha
    host: 192.xxx
    port: 5006
  - platform: musiccast_yamaha
    host: 192.xxx
    port: 5007
  - platform: musiccast_yamaha
    host: 192.xxx
    port: 5008 ,,,

then added thr groups in min media player 
``` entity: media_player.upstairs_lounge_main
group: true
icon: 'mdi:surround-sound'
name: Lounge Yamaha Sound Bar
speaker_group:
  entities:
    - entity_id: media_player.alfresco_main
      name: alfresco
    - entity_id: media_player.upstairs_lounge_main
      name: lounge
  expanded: false
  platform: musiccast_yamaha
type: 'custom:mini-media-player' ```

but still does not work.. must be doing something wrong

**Comment by ppanagiotis** [comment]
Hello, did you put the configuration for mini media player at the ui-lovelace file right?
Can you please paste the entire config of mini media player?

**Comment by jdedfamily** [comment]
‘’’
1
entity: media_player.upstairs_lounge_main
2
group: true
3
icon: 'mdi:surround-sound'
4
name: Lounge Yamaha Sound Bar
5
speaker_group:
6
  entities:
7
    - entity_id: media_player.alfresco_main
8
      name: alfresco
9
    - entity_id: media_player.upstairs_lounge_main
10
      name: lounge
11
  expanded: false
12
  platform: musiccast_yamaha
13
type: 'custom:mini-media-player'
14
volume_stateless: true
15
theme: dark_mint
16

**Comment by ppanagiotis** [comment]
I think I find what's wrong.

The speaker group must be under an entity.

```
id: media_player
icon: mdi:audio-video
title: glance
cards:
  - type: entities
    entities:
      - type: custom:mini-media-player
        group: true
        entity: media_player.livingroom_main #  <------  this is the main entity
        name: LivingRoom
        toggle_power: false
        artwork: cover
        hide:
          icon: true
          power_state: false
        shortcuts:
          buttons:
            - name: Tuner
              icon: mdi:radio
              type: source
              id: tuner
            - name: Spotify
              icon: mdi:spotify
              type: service
              id: switch.turn_on
              data:
                entity_id: switch.spotify
        speaker_group:   # <------ and the speaker group added here
          platform: musiccast_yamaha
          expanded: true
          entities:
            - entity_id: media_player.livingroom_main
              name: Livingroom
            - entity_id: media_player.bedroom_main
              name: Bedroom
            - entity_id: media_player.office_main
              name: Office
            - entity_id: media_player.yard_main
              name: Yard
```
